# -*- coding: utf-8 -*-
"""Authored content, batch A: Parfums de Marly, Mancera, Montale.

Each row: id, gender, family, top, heart, base, description, tags, sure
`sure=False` means I am not confident in the note pyramid and it needs
checking against the house's own copy before this goes live.
"""
A = [
# ── Parfums de Marly (23) ───────────────────────────────────────────────
("pdm-layton","men","amber",
 ["Apple","Bergamot","Mandarin","Lavender"],["Geranium","Violet","Jasmine"],
 ["Vanilla","Cardamom","Sandalwood","Guaiac Wood","Patchouli","Pepper"],
 "The one the whole region asks for by name. Apple and lavender over a vanilla that never quite finishes.",
 ["bestseller","signature"],True),
("pdm-layton-exclusif","men","amber",
 ["Apple","Cardamom","Bergamot"],["Lavender","Jasmine","Orris"],
 ["Vanilla","Sandalwood","Incense","Patchouli"],
 "Layton with the lights down: the same apple opening, resolved into incense and sandalwood instead of sugar.",
 ["signature"],False),
("pdm-pegasus","men","gourmand",
 ["Bitter Almond","Bergamot","Lavender"],["Heliotrope","Jasmine","Orange Blossom"],
 ["Vanilla","Sandalwood","Vetiver","Amberwood"],
 "Almond and heliotrope done without a trace of dessert. The quietest way to be noticed.",
 ["bestseller"],True),
("pdm-althair","men","gourmand",
 ["Bergamot","Almond","Lavender"],["Vanilla","Cinnamon","Orange Blossom"],
 ["Sandalwood","Cedar","Tonka Bean"],
 "Vanilla with its sleeves rolled up — warm, powdery, and far more masculine than it reads on paper.",
 ["bestseller"],True),
("pdm-herod","men","amber",
 ["Cinnamon","Pepper","Osmanthus"],["Tobacco Leaf","Olibanum"],
 ["Vanilla","Vetiver","Labdanum","Cedar"],
 "Sweet tobacco and cinnamon. The cold-weather bottle people buy in Nairobi for the Nakuru evenings.",
 ["bestseller","signature"],True),
("pdm-delina","women","floral",
 ["Rhubarb","Litchi","Bergamot"],["Turkish Rose","Peony","Lily of the Valley"],
 ["Vanilla","Musk","Cashmeran","Incense"],
 "The modern rose: rhubarb and lychee keeping it bright, cashmeran keeping it close to the skin all day.",
 ["bestseller","women"],True),
("pdm-delina-exclusif","women","floral",
 ["Litchi","Rhubarb","Bergamot"],["Turkish Rose","Peony","Orris"],
 ["Vanilla","Musk","Vetiver","Cashmeran"],
 "Delina with the volume up and the sugar down. Rose, still, but wearing a heavier coat.",
 ["women","rare"],False),
("pdm-valaya","women","musk",
 ["Bergamot","Pink Pepper","Mandarin"],["Orange Blossom","Jasmine","Neroli"],
 ["White Musk","Vanilla","Cashmeran"],
 "Clean laundry made expensive. White musk and orange blossom, nothing shouting, everything noticed.",
 ["women","bestseller"],True),
("pdm-valaya-exclusif","women","musk",
 ["Bergamot","Pear","Pink Pepper"],["Orange Blossom","Jasmine","Tuberose"],
 ["White Musk","Vanilla","Sandalwood"],
 "The same soft musk, richer in the base. For the evening version of the same day.",
 ["women"],False),
("pdm-carlisle","men","amber",
 ["Bergamot","Apple","Nutmeg"],["Cinnamon","Jasmine","Patchouli"],
 ["Vanilla","Amber","Sandalwood","Tonka Bean"],
 "Spiced apple over amber — Layton's older cousin, drier and considerably more serious.",
 ["signature"],True),
("pdm-cassili","women","floral",
 ["Mandarin","Pear","Davana"],["Jasmine","Orange Blossom","Rose"],
 ["Vanilla","Musk","Sandalwood"],
 "Pear and jasmine, lifted and kept there. The daytime bottle in a house known for evenings.",
 ["women"],True),
("pdm-godolphin","men","leather",
 ["Saffron","Bergamot","Mandarin"],["Orange Blossom","Cypress","Clary Sage"],
 ["Leather","Oud","Patchouli","Sandalwood"],
 "Saffron and leather with the oud kept on a short leash. A suit, not a statement.",
 ["leather"],True),
("pdm-habdan","unisex","oud",
 ["Bergamot","Cinnamon","Pink Pepper"],["Incense","Rose","Jasmine"],
 ["Oud","Vanilla","Benzoin","Patchouli"],
 "The house's Arabian register: rose and incense folded into oud, built for a climate that eats soft fragrance.",
 ["oud"],True),
("pdm-sedley","unisex","fresh",
 ["Watermint","Bergamot","Mandarin"],["Lavender","Geranium","Violet Leaf"],
 ["Vetiver","White Musk","Amber"],
 "Cold mint and vetiver. The answer when someone says they want something for Mombasa.",
 ["fresh","office"],True),
("pdm-oajan","unisex","oud",
 ["Pear","Saffron","Cinnamon"],["Oud","Rose","Honey"],
 ["Vanilla","Musk","Sandalwood"],
 "Honeyed pear over oud — the sweet end of the Arabian shelf, and the easiest of them to wear.",
 ["oud"],False),
("pdm-oriana","women","gourmand",
 ["Blackcurrant","Guava","Litchi"],["Jasmine","Lily of the Valley","Orange Blossom"],
 ["Vanilla","White Musk","Sandalwood"],
 "Guava and blackcurrant, unapologetically fruity, held together by a musk that keeps it from being a cordial.",
 ["women","new"],False),
("pdm-safanad","women","floral",
 ["Pear","Orange Blossom","Bergamot"],["Iris","Jasmine","Ylang-Ylang"],
 ["Vanilla","Sandalwood","Cedar"],
 "Iris done warm instead of cold — pear and orange blossom over a powdery sandalwood.",
 ["women"],False),
("pdm-meliora","women","gourmand",
 ["Pear","Honey","Bergamot"],["Orange Blossom","Jasmine","Heliotrope"],
 ["Vanilla","Sandalwood","White Musk"],
 "Honey and pear kept just this side of edible. Soft, close, and difficult to put down.",
 ["women","new"],False),
("pdm-palatine","women","floral",
 ["Pear","Bergamot","Pink Pepper"],["Tuberose","Jasmine","Orange Blossom"],
 ["Vanilla","Musk","Sandalwood"],
 "White flowers at full volume, with a vanilla base doing the talking after the first hour.",
 ["women","new"],False),
("pdm-perseus","men","woody",
 ["Bergamot","Mint","Grapefruit"],["Lavender","Geranium","Nutmeg"],
 ["Vetiver","Cedar","Amberwood","Musk"],
 "Clean and green at the top, dry wood underneath. The least sweet thing the house makes.",
 ["new","office"],False),
("pdm-kalan","unisex","amber",
 ["Bergamot","Apple","Cinnamon"],["Lavender","Rum","Orange Blossom"],
 ["Vanilla","Tonka Bean","Sandalwood"],
 "Rum and cinnamon over vanilla — the house at its most convivial.",
 ["signature"],False),
("pdm-percival","men","fresh",
 ["Bergamot","Lavender","Pink Pepper"],["Jasmine","Violet","Orris"],
 ["Ambergris","Cedar","White Musk"],
 "Lavender kept crisp instead of soapy, over ambergris. Office-safe without being invisible.",
 ["office"],False),

# ── Mancera (14) ────────────────────────────────────────────────────────
("mancera-roses-vanille","women","gourmand",
 ["Lemon","Bergamot"],["Bulgarian Rose","Jasmine","Coconut"],
 ["Vanilla","White Musk","Sandalwood","Cedar"],
 "Rose and vanilla with a coconut seam running through it. The best-selling bottle in the house, and it earns it.",
 ["bestseller","value"],True),
("mancera-cedrat-boise","men","citrus",
 ["Sicilian Lemon","Bergamot","Pineapple"],["Leather","Rose","Patchouli"],
 ["Oud","Vanilla","White Musk","Amber"],
 "Lemon over leather and oud — loud, long, and built for heat. Twelve hours is normal.",
 ["bestseller","value"],True),
("mancera-hindu-kush","unisex","oud",
 ["Pink Pepper","Lemon","Cannabis Accord"],["Rose","Oud","Patchouli"],
 ["Vanilla","Amber","White Musk","Sandalwood"],
 "Green, resinous and faintly smoky. The oddest thing on the shelf and a cult object for it.",
 ["oud","rare"],True),
("mancera-instant-crush","women","gourmand",
 ["Raspberry","Bergamot","Blackcurrant"],["Rose","Jasmine","Violet"],
 ["Vanilla","White Musk","Patchouli","Amber"],
 "Red berries and vanilla, close to the skin and slow to leave.",
 ["women","value"],False),
("mancera-intense-french-riviera","unisex","fresh",
 ["Bergamot","Grapefruit","Lemon"],["Marine Accord","Jasmine","Geranium"],
 ["White Musk","Amber","Cedar","Vanilla"],
 "Salt air and citrus with Mancera's usual refusal to fade. Coastal without being a cliché.",
 ["fresh"],False),
("mancera-french-riviera","unisex","fresh",
 ["Bergamot","Lemon","Grapefruit"],["Marine Accord","Orange Blossom","Jasmine"],
 ["White Musk","Amber","Cedar"],
 "The lighter read of the same idea: sea spray, citrus, and a musk that holds it down.",
 ["fresh"],False),
("mancera-aoud-orchid","unisex","oud",
 ["Saffron","Bergamot","Rose"],["Orchid","Oud","Patchouli"],
 ["Leather","Amber","White Musk","Sandalwood"],
 "Orchid and saffron over oud. Floral on the way in, Arabian on the way out.",
 ["oud"],False),
("mancera-roses-greedy","women","gourmand",
 ["Bergamot","Lemon"],["Rose","Jasmine","Caramel"],
 ["Vanilla","Tonka Bean","White Musk","Sandalwood"],
 "Rose dipped in caramel. Sweeter than Roses Vanille and entirely unbothered about it.",
 ["women","value"],False),
("mancera-amore-caffe","unisex","gourmand",
 ["Coffee","Bergamot","Pink Pepper"],["Hazelnut","Jasmine","Cocoa"],
 ["Vanilla","Tonka Bean","White Musk","Sandalwood"],
 "Espresso and hazelnut. Ridiculous on paper, extremely effective on skin.",
 ["gourmand"],False),
("mancera-tonka-cola","unisex","gourmand",
 ["Cola Accord","Bergamot","Lemon"],["Tonka Bean","Cinnamon","Jasmine"],
 ["Vanilla","Amber","White Musk","Sandalwood"],
 "A cola top note that has no business working, over tonka that makes it respectable.",
 ["gourmand"],False),
("mancera-cosmic-pepper","unisex","amber",
 ["Pink Pepper","Grapefruit","Bergamot"],["Rose","Geranium","Cinnamon"],
 ["Amber","Patchouli","White Musk","Vanilla"],
 "Pepper and amber, dry and slightly metallic. Among the house's more grown-up compositions.",
 ["new"],False),
("mancera-sicily","unisex","citrus",
 ["Sicilian Lemon","Bergamot","Orange"],["Neroli","Jasmine","Fig"],
 ["White Musk","Amber","Cedar","Vanilla"],
 "Lemon groves, fig leaf, and enough musk to survive a Nairobi afternoon.",
 ["fresh"],False),
("mancera-melody-of-the-sun","women","gourmand",
 ["Mango","Bergamot","Pineapple"],["Jasmine","Ylang-Ylang","Coconut"],
 ["Vanilla","White Musk","Sandalwood","Amber"],
 "Tropical fruit without the suncream accord. Bright, sweet, and very hard to dislike.",
 ["women","value"],False),
("mancera-xplicit-vanilla","unisex","gourmand",
 ["Bergamot","Pink Pepper"],["Vanilla Orchid","Jasmine","Tonka Bean"],
 ["Vanilla","Benzoin","White Musk","Sandalwood"],
 "Vanilla as the whole argument. No fruit, no flowers, no apology.",
 ["gourmand","new"],False),

# ── Montale (12) ────────────────────────────────────────────────────────
("montale-black-aoud","men","oud",
 ["Rose","Bergamot","Patchouli"],["Oud","Agarwood","Cypriol"],
 ["Musk","Sandalwood","Amber"],
 "The bottle that taught a generation what oud smells like. Rose, smoke and medicine, in that order.",
 ["bestseller","oud","classic"],True),
("montale-starry-nights","unisex","oud",
 ["Bergamot","Lemon","Saffron"],["Rose","Oud","Patchouli"],
 ["Vanilla","Amber","Sandalwood","Musk"],
 "Saffron and oud softened by vanilla — the gentlest way into the house's Aoud line.",
 ["oud","bestseller"],True),
("montale-intense-starry-nights","unisex","oud",
 ["Saffron","Bergamot","Lemon"],["Rose","Oud","Leather"],
 ["Vanilla","Amber","Sandalwood","Musk"],
 "Starry Nights with the oud pushed forward and the vanilla pulled back.",
 ["oud"],False),
("montale-arabians-tonka","unisex","amber",
 ["Saffron","Bergamot","Rose"],["Oud","Tonka Bean","Jasmine"],
 ["Vanilla","Amber","Sandalwood","Musk"],
 "Tonka and saffron over oud. Sweet, dense, and the most-reordered Montale after Black Aoud.",
 ["bestseller","oud"],True),
("montale-arabians","unisex","oud",
 ["Saffron","Rose","Bergamot"],["Oud","Agarwood","Patchouli"],
 ["Amber","Sandalwood","Musk","Leather"],
 "Oud without the sugar — drier and more austere than anything else on this shelf.",
 ["oud"],False),
("montale-chocolate-greedy","unisex","gourmand",
 ["Orange","Bitter Orange"],["Dark Chocolate","Cocoa","Coffee","Dried Fruit"],
 ["Vanilla","Tonka Bean","Patchouli"],
 "Cocoa and orange peel. Easily the most literal fragrance in the room, and it still sells out.",
 ["gourmand","bestseller"],True),
("montale-roses-musk","women","floral",
 ["Rose","Bergamot"],["Bulgarian Rose","Turkish Rose","Jasmine"],
 ["White Musk","Amber","Sandalwood"],
 "Rose and white musk, nothing else in the way. The cleanest rose the house makes.",
 ["women"],True),
("montale-crazy-in-love","women","gourmand",
 ["Raspberry","Bergamot","Pink Pepper"],["Rose","Jasmine","Praline"],
 ["Vanilla","White Musk","Patchouli"],
 "Raspberry and praline over a rose. Young, loud, and extremely popular with its audience.",
 ["women","value"],False),
("montale-intense-cafe-ristretto","unisex","gourmand",
 ["Coffee","Bergamot","Orange"],["Rose","Cocoa","Hazelnut"],
 ["Vanilla","Amber","White Musk","Sandalwood"],
 "Rose and espresso — the house's most copied idea, in its most concentrated form.",
 ["gourmand","bestseller"],False),
("montale-sensual-instinct","unisex","oud",
 ["Saffron","Pink Pepper","Bergamot"],["Oud","Rose","Leather"],
 ["Amber","Vanilla","Sandalwood","Musk"],
 "Leather and saffron over oud, with just enough vanilla to keep it civil.",
 ["oud","new"],False),
("montale-oudyssee","unisex","oud",
 ["Saffron","Bergamot","Cardamom"],["Oud","Rose","Incense"],
 ["Sandalwood","Amber","Musk","Patchouli"],
 "Incense and cardamom folded into oud. Closer to a mosque than a boutique, and better for it.",
 ["oud"],False),
("montale-wood-spices","men","woody",
 ["Cardamom","Nutmeg","Bergamot"],["Cedar","Vetiver","Patchouli"],
 ["Sandalwood","Amber","Musk","Leather"],
 "Dry spice and cedar. The house's quietest bottle and the one that works at a desk.",
 ["office","value"],False),
]

A.append(("pdm-haltane","men","woody",
 ["Juniper Berries","Bergamot","Pink Pepper"],["Lavender","Geranium","Nutmeg"],
 ["Vetiver","Cedar","Amberwood","Musk"],
 "Juniper and vetiver, dry as a gin and twice as persistent. The newest face of the house.",
 ["new"],False))
